# Matrix Manipulations
In this section, we will cover Matrix Manipulations.
First, we will cover the very basics.
Following, we will cover: sparse matrix creation, sparse multiplication, LU decomposition and inverse.
    
To proceed, please import the sparse matrix library: pip install scipy

# Basic Matrix Manipulations
 [Source: https://www.tutorialspoint.com/matrix-manipulation-in-python]

In [1]:
import numpy
# Two matrices are initialized by value
x = numpy.array([[1, 2], [4, 5]])
y = numpy.array([[7, 8], [9, 10]])

In [2]:
#  add()is used to add matrices
print ("Addition of two matrices: ")
print (numpy.add(x,y))
x + y

Addition of two matrices: 
[[ 8 10]
 [13 15]]


array([[ 8, 10],
       [13, 15]])

In [3]:
# divide()is used to divide matrices
# For matrices, there is no such thing as division. You can add, subtract, and multiply matrices, but you cannot divide them.

In [4]:
print ("Multiplication of two matrices: ") # DOT Product
print (numpy.multiply(x,y))
x * y

Multiplication of two matrices: 
[[ 7 16]
 [36 50]]


array([[ 7, 16],
       [36, 50]])

In [5]:
print ("The product of two matrices : ") # Regular multiplicaton
print (numpy.dot(x,y))
x @ y

The product of two matrices : 
[[25 28]
 [73 82]]


array([[25, 28],
       [73, 82]])

In [6]:
print ("square root is : ")
print (numpy.sqrt(x))

square root is : 
[[1.         1.41421356]
 [2.         2.23606798]]


In [7]:
print ("The summation of elements : ")
print (numpy.sum(y))

The summation of elements : 
34


In [9]:
print ("The column wise summation  : ")
print (numpy.sum(y,axis=0))

The column wise summation  : 
[16 18]


In [10]:
print ("The row wise summation: ")
print (numpy.sum(y,axis=1))

The row wise summation: 
[15 19]


In [11]:
# using "T" to transpose the matrix
print ("Matrix transposition : ")
print (x.T)

Matrix transposition : 
[[1 4]
 [2 5]]


# Sparse Matrices
Sparse Matrices are matrices that contain lots of empty cells. It is important to classify matrices as sparse matrices because, by doing so, you can minimize using lots of memory.

Many linear algebra NumPy and SciPy functions that operate on NumPy arrays can transparently operate on SciPy sparse arrays.

## Sparse Matrix Creation
[Source: https://www.educative.io/edpresso/sparse-matrices-in-python ]

In [8]:
# Import the libraries
import numpy as np
from scipy.sparse import csr_matrix

In [9]:
# create a 2-D representation of the matrix
A = np.array([[1, 0, 0, 0, 0, 0], [0, 0, 2, 0, 0, 1],
 [0, 0, 0, 2, 0, 0]])
print("Dense matrix representation: \n", A)

Dense matrix representation: 
 [[1 0 0 0 0 0]
 [0 0 2 0 0 1]
 [0 0 0 2 0 0]]


In [10]:
# Simple Matrix Multiplication
m = np.array([[1,0, 0],[0,5,6],[0,8,0]])
c = np.array([0,1,2])
m * c

array([[ 0,  0,  0],
       [ 0,  5, 12],
       [ 0,  8,  0]])

In [11]:
# Sparse Matrix Multiplication
T = csr_matrix(m).multiply(csr_matrix(c))
print(T)

  (1, 2)	12
  (1, 1)	5
  (2, 1)	8


In [12]:
T.todense()

matrix([[ 0,  0,  0],
        [ 0,  5, 12],
        [ 0,  8,  0]], dtype=int32)

# Other Sparse Matrix Operations
[Source: https://www.w3schools.com/python/scipy_sparse_data.asp ]

In [13]:
# Nonzeros
# m = [[1,0, 0],[0,5,6],[0,8,0]]
print("Non-zeros:", csr_matrix(m).data)
# Number of zeros
print("Number of non-zeros:", csr_matrix(m).count_nonzero())

Non-zeros: [1 5 6 8]
Number of non-zeros: 4


In [14]:
# You can do operations between sparse and dense. But I do not recommend it.
m + csr_matrix(m)

matrix([[ 2,  0,  0],
        [ 0, 10, 12],
        [ 0, 16,  0]])

# LU Decomposition
In numerical analysis and linear algebra, lower–upper (LU) decomposition or factorization factors a matrix as the product of a lower triangular matrix and an upper triangular matrix. The product sometimes includes a permutation matrix as well. LU decomposition can be viewed as the matrix form of Gaussian elimination. Computers usually solve square systems of linear equations using LU decomposition, and it is also a key step when inverting a matrix or computing the determinant of a matrix. The LU decomposition was introduced by the Polish mathematician Tadeusz Banachiewicz in 1938
[Sources: https://en.wikipedia.org/wiki/LU_decomposition , https://pythonhosted.org/ad/linalg.html ]

In [15]:
# Example 1
import numpy as np
import scipy.linalg as la

A = [[1, 3, 5],
      [2, 4, 7],
      [1, 1, 0]]

P, L, U = la.lu(A) # Order of P, L, U is important! P= Permutation, L= Lower, U= Upper

In [16]:
L

array([[ 1. ,  0. ,  0. ],
       [ 0.5,  1. ,  0. ],
       [ 0.5, -1. ,  1. ]])

In [17]:
U

array([[ 2. ,  4. ,  7. ],
       [ 0. ,  1. ,  1.5],
       [ 0. ,  0. , -2. ]])

In [18]:
P

array([[0., 1., 0.],
       [1., 0., 0.],
       [0., 0., 1.]])

In [19]:
# Example 2
A = [[11,  9, 24, 2],
      [ 1,  5,  2, 6],
      [ 3, 17, 18, 1],
      [ 2,  5,  7, 1]]

P, L, U = la.lu(A)

In [20]:
P

array([[1., 0., 0., 0.],
       [0., 0., 1., 0.],
       [0., 1., 0., 0.],
       [0., 0., 0., 1.]])

In [21]:
L

array([[1.        , 0.        , 0.        , 0.        ],
       [0.27272727, 1.        , 0.        , 0.        ],
       [0.09090909, 0.2875    , 1.        , 0.        ],
       [0.18181818, 0.23125   , 0.00359712, 1.        ]])

In [22]:
U

array([[11.        ,  9.        , 24.        ,  2.        ],
       [ 0.        , 14.54545455, 11.45454545,  0.45454545],
       [ 0.        ,  0.        , -3.475     ,  5.6875    ],
       [ 0.        ,  0.        ,  0.        ,  0.51079137]])

# Inverse Matrix

In [23]:
import numpy as np
A = np.array(([1,3,3],[1,4,3],[1,3,4]))
A

array([[1, 3, 3],
       [1, 4, 3],
       [1, 3, 4]])

In [24]:
A_inv = np.linalg.inv(A)
A_inv

array([[ 7., -3., -3.],
       [-1.,  1.,  0.],
       [-1.,  0.,  1.]])

In [25]:
# To check inverse is correct
A_inv.dot(A)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

# QUIZ

First find the LU Decomposition of

A = [[1, 3, 1],
      [4, 9, 2],
      [6, 2, 9]]

Then find the Inverse Matrix of the Lower matrix

Then confirm that this inverse is correct.

In [26]:
# SOLUTION
import numpy as np
import scipy.linalg as la

A = [[1, 3, 1],
      [4, 9, 2],
      [6, 2, 9]]

P, L, U = la.lu(A) # Order of P, L, U is important! P= Permutation, L= Lower, U= Upper

L

array([[1.        , 0.        , 0.        ],
       [0.66666667, 1.        , 0.        ],
       [0.16666667, 0.34782609, 1.        ]])

In [27]:
L_inv = np.linalg.inv(L)
L_inv

array([[ 1.        ,  0.        ,  0.        ],
       [-0.66666667,  1.        ,  0.        ],
       [ 0.06521739, -0.34782609,  1.        ]])

In [28]:
L_inv.dot(L)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])