# Special Function in Thiago's Paper
[Source: https://ieeexplore.ieee.org/document/8511780 ]

In [1]:
import numpy as np

# Diagonal Matrix
print("diagflat default diagonal : \n", np.diagflat([51, 67, 69]))
print("diagflat above main diagonal : \n", np.diagflat([51, 67, 69], 1))
print("diagflat above main diagonal : \n", np.diagflat([51, 67, 69], 2))


diagflat default diagonal : 
 [[51  0  0]
 [ 0 67  0]
 [ 0  0 69]]
diagflat above main diagonal : 
 [[ 0 51  0  0]
 [ 0  0 67  0]
 [ 0  0  0 69]
 [ 0  0  0  0]]
diagflat above main diagonal : 
 [[ 0  0 51  0  0]
 [ 0  0  0 67  0]
 [ 0  0  0  0 69]
 [ 0  0  0  0  0]
 [ 0  0  0  0  0]]


In [2]:
# Identity Matrix
print("Identity matrix : \n", np.eye(5))

Identity matrix : 
 [[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]


In [3]:
# Get the conjugate
print("Conjugate : \n", np.conj(1+2j))
print("Conjugate : \n", np.conjugate(1+2j))

Conjugate : 
 (1-2j)
Conjugate : 
 (1-2j)


In [4]:
# Real and Imagery Components
num = 1 - 5j
print("Real : \n", num.real)
print("Imagery : \n", num.imag)

Real : 
 1.0
Imagery : 
 -5.0


In [5]:
# Zero Matrix
print("Zero Matrix : \n", np.zeros((6, 6)))

Zero Matrix : 
 [[0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]]


In [7]:
# Exponential Function: exp(x) = e^x where e= 2.718281(approx)
ar=np.array([1,2,3])
ar=np.exp(ar)
print("Exponential Results : \n", ar)

Exponential Results : 
 [ 2.71828183  7.3890561  20.08553692]


In [8]:
# Vertical Stack 1
a = np.array([1, 2, 3])
b = np.array([2, 3, 4])
print("Vertical Stack 1 : \n", np.vstack((a,b)))

print()

Vertical Stack 1 : 
 [[1 2 3]
 [2 3 4]]



In [9]:
# Horizontal Stack 1
a = np.array((1,2,3))
b = np.array((2,3,4))
print("Horizontal Stack 1 : \n", np.hstack((a,b)))

print()


Horizontal Stack 1 : 
 [1 2 3 2 3 4]



# HOMEWORK
Stack vertically a 5x5 identity matrix with a 5x5 zero matrix.

In [9]:
# SOLUTION
import numpy as np

np.vstack((np.eye(5),np.zeros((5,5))))

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])